image: abaez/luarocks

test:
  stage: test
  before_script:
    - luarocks install --local luacheck
    - luarocks install --local busted
  script:
    - $HOME/.luarocks/bin/luacheck .
    - $HOME/.luarocks/bin/busted .
